### ISSUE TITLE
Blog index page loading

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#230]

**Comment by phil-linnell** [comment]
We seem to be waiting for both page content and posts APIs before the content (i.e. the hero image and text) is loaded. Makes for a nasty experience where we just see a blue screen with only the blog categories dropdown box.

Try to force the content to load first?

**Comment by daaain** [comment]
So this is mainly about changing the order of animation, so that the hero transitions in while content is loading.

**Comment by collingo** [comment]
There's a lot going on here.

- Firstly every page has it's own set of data requirements. In the case of the blog page, this comes from 2 endpoints, the page data (title, images etc) and the posts data - the latter of which is pretty slow. The current implementation waits for all these requests to return before rendering the page, hence the long delay. I plan to fix this by rendering the page when each request returns.

- The second issue will be having decent loading animations for both the page data and the posts list. We may need to have a think about how's best to approach this once the first issue is resolved.

**Comment by collingo** [comment]
Additionally, all the posts are returned in the page response. This was initially done to reduce the number of requests. It turned out we needed a separate endpoint for post fetching to facilitate pagination and filtering. Now we have the two endpoints we don't need posts in the page response which will speed it up considerably. I will log an issue for the backend/WP guys to pick up.

**Comment by collingo** [comment]
Fixed on the bootstrapper branch as I relied on these changes to be in place for the cleanest solution and to prevent merge conflicts later. This branch has a nice little dependency chain that must be satisfied before it can be released to prod so there might be a slight delay to this ticket now.

The second issue might not be such a problem as it turns out :)
