### ISSUE TITLE
Fix quote-block component

### ISSUE THREAD

**Issue by phil-linnell** [ustwo/ustwo.com-frontend#244]
For when an author wants to use a large, bold blockquote.

Seems to working ok except no background colour is being applied. Also it would need to be a full width component.

**Comment by ch2ch3** [comment]
Hmm just had a look, need a catchup around this! Looks like it's already full-width and applying a background colour works OK for me, but

1. the default styling without a background colour looks pretty bad and
2. the design on the server applies colour to the text and quotemark rather than a background colour
